# Generated by Django 2.1.1 on 2018-10-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('suburb', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('WA', 'WA'), ('NT', 'NT'), ('QLD', 'QLD'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('ACT', 'ACT'), ('TAS', 'TAS'), ('SA', 'SA')], max_length=3)),
                ('postcode', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person')),
            ],
        ),
    ]
